name: multiverse_multivi
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - ipykernel
  - python=3.11
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - scvi-tools==1.2.0
  - scanpy==1.10.3
  - pip:
      - muon==0.1.7
      - louvain==0.8.2
