globals:
  experiment_name: benchmark_run
  random_seed: 42
  run_user_params: true
  run_gridsearch: false
jobs:
- dataset_slug: pbmc10k
  model_name: Cobolt
  model_params:
    device: cpu
    latent_dimensions: 20
    learning_rate: 0.001
    num_epochs: 20
    umap_random_state: 42
    umap_color_type: cell_type
    random_state: 42
- dataset_slug: pbmc10k
  model_name: MOFA
  model_params:
    device: cpu
    n_iterations: 5
    n_factors: 20
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: pbmc10k
  model_name: Mowgli
  model_params:
    device: cpu
    latent_dimensions: 20
    optimizer: adam
    learning_rate: 0.001
    tol_inner: 1.0e-06
    max_iter_inner: 5
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: pbmc10k
  model_name: MultiVI
  model_params:
    device: cpu
    max_epochs: 400
    learning_rate: 0.001
    latent_dimensions: 20
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: pbmc10k
  model_name: PCA
  model_params:
    n_components: 50
    device: cpu
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: teaseq
  model_name: Cobolt
  model_params:
    device: cpu
    latent_dimensions: 20
    learning_rate: 0.001
    num_epochs: 2
    umap_random_state: 42
    umap_color_type: cell_type
    random_state: 42
- dataset_slug: teaseq
  model_name: MOFA
  model_params:
    device: cpu
    n_iterations: 5
    n_factors: 20
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: teaseq
  model_name: Mowgli
  model_params:
    device: cpu
    latent_dimensions: 20
    optimizer: adam
    learning_rate: 0.001
    tol_inner: 1.0e-06
    max_iter_inner: 500
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: teaseq
  model_name: MultiVI
  model_params:
    device: cpu
    max_epochs: 4
    learning_rate: 0.001
    latent_dimensions: 20
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: teaseq
  model_name: PCA
  model_params:
    n_components: 50
    device: cpu
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: teaseq
  model_name: TotalVI
  model_params:
    device: cpu
    max_epochs: 4
    learning_rate: 0.001
    latent_dimensions: 20
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: gtex_v9
  model_name: PCA
  model_params:
    n_components: 50
    device: cpu
    umap_random_state: 42
    umap_color_type: cell_type
