globals:
  experiment_name: benchmark_run
  random_seed: 42
  run_user_params: true
  run_gridsearch: false
jobs:
- dataset_slug: pbmc10k
  model_name: MOFA
  model_params:
    device: cuda
    n_iterations: 5
    n_factors: 20
    umap_random_state: 42
    umap_color_type: cell_type
  mem_limit: 16g
  gpu: true
- dataset_slug: pbmc10k
  model_name: PCA
  model_params:
    n_components: 50
    device: cpu
    umap_random_state: 42
    umap_color_type: cell_type
  mem_limit: 16g
