globals:
  experiment_name: benchmark_run
  random_seed: 42
  run_user_params: true
  run_gridsearch: false
jobs:
- dataset_slug: pbmc10k
  model_name: Cobolt
  model_params:
    device: cuda:0
    latent_dimensions: 2
    learning_rate: 0.001
    num_epochs: 10
    umap_random_state: 42
    umap_color_type: cell_type
    random_state: 42
- dataset_slug: pbmc10k
  model_name: MOFA
  model_params:
    device: cuda:0
    n_iterations: 10
    n_factors: 2
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: pbmc10k
  model_name: Mowgli
  model_params:
    device: cuda:0
    latent_dimensions: 2
    optimizer: adam
    learning_rate: 0.001
    tol_inner: 1.0e-06
    max_iter_inner: 10
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: pbmc10k
  model_name: MultiVI
  model_params:
    device: cuda:0
    max_epochs: 10
    learning_rate: 0.001
    latent_dimensions: 2
    umap_random_state: 42
    umap_color_type: cell_type
- dataset_slug: pbmc10k
  model_name: PCA
  model_params:
    n_components: 10
    device: cpu
    umap_random_state: 42
    umap_color_type: cell_type
