name: multiverse_mowgli
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - ipykernel
  - python=3.11
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - scanpy==1.10.3
  - scikit-misc==0.5.2
  - pip:
      - mowgli==0.1.0
      - muon==0.1.7
      - jaxlib==0.4.34


