name: multiverse_mofa_cpu
channels:
  - conda-forge
dependencies:
  - pip
  - ipykernel
  - python=3.11
  - pytorch
  - scanpy==1.10.3
  - scikit-misc==0.5.2
  
  - pip:
      - mofapy2==0.7.2
      - muon==0.1.7
